plugins:
  - jekyll-feed
theme: jekyll-theme-hacker
author: Mike Levin
permalink: /:slug/
gaid: G-L7L2XR3J2G
title: Mike At Eleven | MikeAtEleven.com
description: Welcome to the Mike At Eleven | MikeAtEleven.com Website!
tagline: Mike At Eleven
welcome: Welcome to the Mike At Eleven Website!
apex: MikeAtEleven.com